;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1
	.word @sfx_ntsc_2
	.word @sfx_ntsc_3
	.word @sfx_ntsc_4
	.word @sfx_ntsc_5
	.word @sfx_ntsc_6
	.word @sfx_ntsc_7

@pal:
;	.word @sfx_pal_0
;	.word @sfx_pal_1
;	.word @sfx_pal_2
;	.word @sfx_pal_3

@sfx_ntsc_0:
	.byte $80,$bf,$81,$ab,$82,$01,$01,$81,$52,$01,$81,$ef,$82,$00,$04,$00
@sfx_ntsc_1:
	.byte $80,$bf,$81,$b5,$82,$01,$01,$81,$f3,$01,$81,$6a,$82,$02,$04,$00
@sfx_ntsc_2:
	.byte $89,$3f,$8a,$08,$01,$89,$3b,$8a,$02,$01,$89,$38,$01,$89,$35,$8a
	.byte $01,$01,$89,$33,$01,$00
@sfx_ntsc_3:
	.byte $86,$81,$87,$6a,$88,$00,$01,$87,$70,$01,$87,$6a,$01,$87,$70,$01
	.byte $87,$6a,$01,$86,$00,$00
@sfx_ntsc_4:
	.byte $80,$bf,$81,$00,$82,$00,$01,$80,$bc,$81,$39,$01,$80,$ba,$81,$8b
	.byte $01,$80,$b6,$81,$0a,$82,$01,$01,$00
@sfx_ntsc_5:
	.byte $86,$81,$87,$d5,$88,$00,$02,$87,$8e,$02,$87,$5e,$02,$87,$3f,$02
	.byte $00
@sfx_ntsc_6:
	.byte $86,$81,$87,$3f,$88,$00,$02,$87,$54,$02,$87,$70,$02,$87,$96,$02
	.byte $00
@sfx_ntsc_7:
	.byte $86,$81,$87,$3f,$88,$00,$01,$87,$7e,$03,$87,$31,$01,$87,$64,$03
	.byte $87,$29,$01,$87,$54,$03,$87,$1f,$01,$87,$3f,$03,$00
