;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.dw .ntsc
	.dw .pal
.ntsc:
	.dw .sfx_ntsc_0
.pal:
	.dw .sfx_pal_0

.sfx_ntsc_0:
	.db $86,$81,$87,$3f,$88,$00,$01,$87,$7e,$03,$87,$31,$01,$87,$64,$03
	.db $87,$29,$01,$87,$54,$03,$87,$1f,$01,$87,$3f,$03,$00
.sfx_pal_0:
	.db $86,$81,$87,$3a,$88,$00,$01,$87,$75,$03,$87,$2e,$01,$87,$5d,$02
	.db $87,$26,$01,$87,$4e,$02,$87,$1d,$01,$87,$3a,$03,$00
