;this file for FamiTone2 library generated by text2data tool

music01_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,409,341

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $01
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c1,$c3,$c6,$ca,$cf,$00,$04
@env2:
	.byte $cf,$00,$00


@song0ch0:
	.byte $fb,$07
@song0ch0loop:
@ref0:
	.byte $82,$44,$46,$44,$46,$44,$00,$3e,$00,$40,$00,$44,$00,$4a,$00,$4e
	.byte $00
@ref1:
	.byte $4b,$45,$41,$3f,$41,$39,$3a,$85
@ref2:
	.byte $44,$46,$44,$46,$44,$00,$3e,$00,$40,$00,$44,$00,$4a,$00,$4e,$00
@ref3:
	.byte $51,$53,$55,$57,$59,$53,$4b,$00,$81
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref4:
	.byte $9f
@ref5:
	.byte $9f
@ref6:
	.byte $9f
@ref7:
	.byte $9f
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref8:
	.byte $84,$33,$3a,$00,$40,$00,$83,$46,$00,$83,$44,$00,$83
@ref9:
	.byte $40,$00,$3e,$00,$40,$00,$83,$38,$00,$3a,$00,$38,$00,$3a,$00
@ref10:
	.byte $33,$3a,$00,$40,$00,$83,$46,$00,$83,$44,$00,$83
	.byte $ff,$0f
	.word @ref9
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref12:
	.byte $9f
@ref13:
	.byte $9f
@ref14:
	.byte $9f
@ref15:
	.byte $9f
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref16:
	.byte $9f
@ref17:
	.byte $9f
@ref18:
	.byte $9f
@ref19:
	.byte $9f
	.byte $fd
	.word @song0ch4loop
