;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
@pal:
	.word @sfx_pal_0

@sfx_ntsc_0:
	.byte $86,$81,$87,$3f,$88,$00,$02,$87,$54,$02,$87,$70,$02,$87,$96,$02
	.byte $00
@sfx_pal_0:
	.byte $86,$81,$87,$3a,$88,$00,$02,$87,$4e,$02,$87,$68,$01,$87,$8b,$02
	.byte $00
