;this file for FamiTone2 library generated by text2data tool

Untitled_music_data:
	.db 1
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256

.instruments:
	.db $30 ;instrument $00
	.dw .env0,.env0,.env0
	.db $00

.samples:
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;1
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;2
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;3
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;4
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;5
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;6
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;7
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;8
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;9
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;10
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;11
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;12
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;13
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;14
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;15
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;16
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;17
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;18
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;19
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;20
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;21
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;22
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;23
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;24
	.db $00+LOW(FT_DPCM_PTR),$91,$0f	;25
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;26
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;27
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;28
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;29
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;30
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;31
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;32
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;33
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;34
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;35
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;36
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;37
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;38
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;39
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;40
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;41
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;42
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;43
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;44
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;45
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;46
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;47
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;48
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;49
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;50
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;51
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;52
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;53
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;54
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;55
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;56
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;57
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;58
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;59
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;60
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;61
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;62
	.db $00+LOW(FT_DPCM_PTR),$00,$00	;63

.env0:
	.db $c0,$00,$00


.song0ch0:
	.db $fb,$06
.song0ch0loop:
.ref0:
	.db $a1
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref1:
	.db $a1
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref2:
	.db $a1
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref3:
	.db $a1
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref4:
	.db $32,$9f
	.db $fd
	.dw .song0ch4loop
