;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
@pal:
	.word @sfx_pal_0

@sfx_ntsc_0:
	.byte $80,$3f,$81,$94,$82,$01,$01,$81,$71,$01,$81,$2e,$01,$81,$fc,$82
	.byte $00,$01,$81,$e8,$01,$81,$e2,$00
@sfx_pal_0:
	.byte $80,$3f,$81,$75,$82,$01,$01,$81,$52,$01,$81,$0f,$01,$81,$dd,$82
	.byte $00,$01,$81,$c9,$00
